/*
 * This file is generated by jOOQ.
 */
package com.imjava.dbshow.db.tables;


import com.imjava.dbshow.db.Dbshow;
import com.imjava.dbshow.db.Indexes;
import com.imjava.dbshow.db.Keys;
import com.imjava.dbshow.db.tables.records.DataRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Data extends TableImpl<DataRecord> {

    private static final long serialVersionUID = 1298828064;

    /**
     * The reference instance of <code>dbshow.data</code>
     */
    public static final Data DATA = new Data();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataRecord> getRecordType() {
        return DataRecord.class;
    }

    /**
     * The column <code>dbshow.data.id</code>.
     */
    public final TableField<DataRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>dbshow.data.data</code>.
     */
    public final TableField<DataRecord, Double> DATA_ = createField(DSL.name("data"), org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>dbshow.data.country</code>.
     */
    public final TableField<DataRecord, String> COUNTRY = createField(DSL.name("country"), org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>dbshow.data.year</code>.
     */
    public final TableField<DataRecord, String> YEAR = createField(DSL.name("year"), org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>dbshow.data.third_index_id</code>.
     */
    public final TableField<DataRecord, Integer> THIRD_INDEX_ID = createField(DSL.name("third_index_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>dbshow.data</code> table reference
     */
    public Data() {
        this(DSL.name("data"), null);
    }

    /**
     * Create an aliased <code>dbshow.data</code> table reference
     */
    public Data(String alias) {
        this(DSL.name(alias), DATA);
    }

    /**
     * Create an aliased <code>dbshow.data</code> table reference
     */
    public Data(Name alias) {
        this(alias, DATA);
    }

    private Data(Name alias, Table<DataRecord> aliased) {
        this(alias, aliased, null);
    }

    private Data(Name alias, Table<DataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Data(Table<O> child, ForeignKey<O, DataRecord> key) {
        super(child, key, DATA);
    }

    @Override
    public Schema getSchema() {
        return Dbshow.DBSHOW;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATA_DATA_THIRD_INDEX_ID_FK, Indexes.DATA_PRIMARY);
    }

    @Override
    public Identity<DataRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DATA;
    }

    @Override
    public UniqueKey<DataRecord> getPrimaryKey() {
        return Keys.KEY_DATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<DataRecord>> getKeys() {
        return Arrays.<UniqueKey<DataRecord>>asList(Keys.KEY_DATA_PRIMARY);
    }

    @Override
    public List<ForeignKey<DataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DataRecord, ?>>asList(Keys.DATA_THIRD_INDEX_ID_FK);
    }

    public ThirdIndex thirdIndex() {
        return new ThirdIndex(this, Keys.DATA_THIRD_INDEX_ID_FK);
    }

    @Override
    public Data as(String alias) {
        return new Data(DSL.name(alias), this);
    }

    @Override
    public Data as(Name alias) {
        return new Data(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Data rename(String name) {
        return new Data(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Data rename(Name name) {
        return new Data(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Double, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
