/*
 * This file is generated by jOOQ.
 */
package com.imjava.dbshow.db.tables;


import com.imjava.dbshow.db.Dbshow;
import com.imjava.dbshow.db.Indexes;
import com.imjava.dbshow.db.Keys;
import com.imjava.dbshow.db.tables.records.SecondIndexRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 二级指标
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecondIndex extends TableImpl<SecondIndexRecord> {

    private static final long serialVersionUID = 1622982248;

    /**
     * The reference instance of <code>dbshow.second_index</code>
     */
    public static final SecondIndex SECOND_INDEX = new SecondIndex();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecondIndexRecord> getRecordType() {
        return SecondIndexRecord.class;
    }

    /**
     * The column <code>dbshow.second_index.id</code>.
     */
    public final TableField<SecondIndexRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>dbshow.second_index.name</code>.
     */
    public final TableField<SecondIndexRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>dbshow.second_index.first_index_id</code>.
     */
    public final TableField<SecondIndexRecord, Integer> FIRST_INDEX_ID = createField(DSL.name("first_index_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>dbshow.second_index</code> table reference
     */
    public SecondIndex() {
        this(DSL.name("second_index"), null);
    }

    /**
     * Create an aliased <code>dbshow.second_index</code> table reference
     */
    public SecondIndex(String alias) {
        this(DSL.name(alias), SECOND_INDEX);
    }

    /**
     * Create an aliased <code>dbshow.second_index</code> table reference
     */
    public SecondIndex(Name alias) {
        this(alias, SECOND_INDEX);
    }

    private SecondIndex(Name alias, Table<SecondIndexRecord> aliased) {
        this(alias, aliased, null);
    }

    private SecondIndex(Name alias, Table<SecondIndexRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("二级指标"));
    }

    public <O extends Record> SecondIndex(Table<O> child, ForeignKey<O, SecondIndexRecord> key) {
        super(child, key, SECOND_INDEX);
    }

    @Override
    public Schema getSchema() {
        return Dbshow.DBSHOW;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SECOND_INDEX_PRIMARY, Indexes.SECOND_INDEX_SECOND_INDEX_FIRST_INDEX_ID_FK);
    }

    @Override
    public Identity<SecondIndexRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SECOND_INDEX;
    }

    @Override
    public UniqueKey<SecondIndexRecord> getPrimaryKey() {
        return Keys.KEY_SECOND_INDEX_PRIMARY;
    }

    @Override
    public List<UniqueKey<SecondIndexRecord>> getKeys() {
        return Arrays.<UniqueKey<SecondIndexRecord>>asList(Keys.KEY_SECOND_INDEX_PRIMARY);
    }

    @Override
    public List<ForeignKey<SecondIndexRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SecondIndexRecord, ?>>asList(Keys.SECOND_INDEX_FIRST_INDEX_ID_FK);
    }

    public FirstIndex firstIndex() {
        return new FirstIndex(this, Keys.SECOND_INDEX_FIRST_INDEX_ID_FK);
    }

    @Override
    public SecondIndex as(String alias) {
        return new SecondIndex(DSL.name(alias), this);
    }

    @Override
    public SecondIndex as(Name alias) {
        return new SecondIndex(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecondIndex rename(String name) {
        return new SecondIndex(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecondIndex rename(Name name) {
        return new SecondIndex(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
