/*
 * This file is generated by jOOQ.
 */
package com.imjava.dbshow.db;


import com.imjava.dbshow.db.tables.Data;
import com.imjava.dbshow.db.tables.FirstIndex;
import com.imjava.dbshow.db.tables.SecondIndex;
import com.imjava.dbshow.db.tables.ThirdIndex;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dbshow
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dbshow.data</code>.
     */
    public static final Data DATA = Data.DATA;

    /**
     * 一级指标
     */
    public static final FirstIndex FIRST_INDEX = FirstIndex.FIRST_INDEX;

    /**
     * 二级指标
     */
    public static final SecondIndex SECOND_INDEX = SecondIndex.SECOND_INDEX;

    /**
     * 三级指标
     */
    public static final ThirdIndex THIRD_INDEX = ThirdIndex.THIRD_INDEX;
}
