/*
 * This file is generated by jOOQ.
 */
package com.imjava.dbshow.db;


import com.imjava.dbshow.db.tables.Metrics;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dbshow
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dbshow.metrics</code>.
     */
    public static final Metrics METRICS = Metrics.METRICS;
}
