/*
 * This file is generated by jOOQ.
 */
package com.imjava.dbshow.db.tables.records;


import com.imjava.dbshow.db.tables.Data;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataRecord extends UpdatableRecordImpl<DataRecord> implements Record5<Integer, Double, String, String, Integer> {

    private static final long serialVersionUID = 826197664;

    /**
     * Setter for <code>dbshow.data.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dbshow.data.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dbshow.data.data</code>.
     */
    public void setData(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>dbshow.data.data</code>.
     */
    public Double getData() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>dbshow.data.country</code>.
     */
    public void setCountry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dbshow.data.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dbshow.data.year</code>.
     */
    public void setYear(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dbshow.data.year</code>.
     */
    public String getYear() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dbshow.data.third_index_id</code>.
     */
    public void setThirdIndexId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dbshow.data.third_index_id</code>.
     */
    public Integer getThirdIndexId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Double, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Double, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Data.DATA.ID;
    }

    @Override
    public Field<Double> field2() {
        return Data.DATA.DATA_;
    }

    @Override
    public Field<String> field3() {
        return Data.DATA.COUNTRY;
    }

    @Override
    public Field<String> field4() {
        return Data.DATA.YEAR;
    }

    @Override
    public Field<Integer> field5() {
        return Data.DATA.THIRD_INDEX_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Double component2() {
        return getData();
    }

    @Override
    public String component3() {
        return getCountry();
    }

    @Override
    public String component4() {
        return getYear();
    }

    @Override
    public Integer component5() {
        return getThirdIndexId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Double value2() {
        return getData();
    }

    @Override
    public String value3() {
        return getCountry();
    }

    @Override
    public String value4() {
        return getYear();
    }

    @Override
    public Integer value5() {
        return getThirdIndexId();
    }

    @Override
    public DataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DataRecord value2(Double value) {
        setData(value);
        return this;
    }

    @Override
    public DataRecord value3(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public DataRecord value4(String value) {
        setYear(value);
        return this;
    }

    @Override
    public DataRecord value5(Integer value) {
        setThirdIndexId(value);
        return this;
    }

    @Override
    public DataRecord values(Integer value1, Double value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataRecord
     */
    public DataRecord() {
        super(Data.DATA);
    }

    /**
     * Create a detached, initialised DataRecord
     */
    public DataRecord(Integer id, Double data, String country, String year, Integer thirdIndexId) {
        super(Data.DATA);

        set(0, id);
        set(1, data);
        set(2, country);
        set(3, year);
        set(4, thirdIndexId);
    }
}
