/*
 * This file is generated by jOOQ.
 */
package com.imjava.dbshow.db.tables.records;


import com.imjava.dbshow.db.tables.FirstIndex;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 一级指标
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FirstIndexRecord extends UpdatableRecordImpl<FirstIndexRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 62497428;

    /**
     * Setter for <code>dbshow.first_index.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dbshow.first_index.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dbshow.first_index.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dbshow.first_index.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FirstIndex.FIRST_INDEX.ID;
    }

    @Override
    public Field<String> field2() {
        return FirstIndex.FIRST_INDEX.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public FirstIndexRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FirstIndexRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public FirstIndexRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FirstIndexRecord
     */
    public FirstIndexRecord() {
        super(FirstIndex.FIRST_INDEX);
    }

    /**
     * Create a detached, initialised FirstIndexRecord
     */
    public FirstIndexRecord(Integer id, String name) {
        super(FirstIndex.FIRST_INDEX);

        set(0, id);
        set(1, name);
    }
}
