/*
 * This file is generated by jOOQ.
 */
package com.imjava.dbshow.db.tables.records;


import com.imjava.dbshow.db.tables.SecondIndex;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 二级指标
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecondIndexRecord extends UpdatableRecordImpl<SecondIndexRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 467410148;

    /**
     * Setter for <code>dbshow.second_index.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dbshow.second_index.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dbshow.second_index.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dbshow.second_index.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dbshow.second_index.first_index_id</code>.
     */
    public void setFirstIndexId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dbshow.second_index.first_index_id</code>.
     */
    public Integer getFirstIndexId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SecondIndex.SECOND_INDEX.ID;
    }

    @Override
    public Field<String> field2() {
        return SecondIndex.SECOND_INDEX.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return SecondIndex.SECOND_INDEX.FIRST_INDEX_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getFirstIndexId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getFirstIndexId();
    }

    @Override
    public SecondIndexRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SecondIndexRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SecondIndexRecord value3(Integer value) {
        setFirstIndexId(value);
        return this;
    }

    @Override
    public SecondIndexRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecondIndexRecord
     */
    public SecondIndexRecord() {
        super(SecondIndex.SECOND_INDEX);
    }

    /**
     * Create a detached, initialised SecondIndexRecord
     */
    public SecondIndexRecord(Integer id, String name, Integer firstIndexId) {
        super(SecondIndex.SECOND_INDEX);

        set(0, id);
        set(1, name);
        set(2, firstIndexId);
    }
}
